import type {
  Diagnostic,
  ErrorCatalog,
  ScanResult,
  Severity,
  SourceLocation,
} from "./types.js";

export function renderConsole(
  result: ScanResult,
  diagnostics = result.diagnostics,
): string {
  const lines: string[] = [];
  for (const diagnostic of diagnostics) {
    const location = diagnostic.location
      ? `${diagnostic.location.file}:${diagnostic.location.line}:${diagnostic.location.column}`
      : "project";
    lines.push(
      `${severityMark(diagnostic.severity)} ${location} [${diagnostic.ruleId}] ${diagnostic.message}`,
    );
  }

  const structured = result.errors.filter((item) => item.structured).length;
  const counts = countSeverities(diagnostics);
  if (lines.length) lines.push("");
  lines.push(
    `Scanned ${result.filesScanned} files · ${structured} structured errors · ` +
      `${counts.error} errors · ${counts.warning} warnings · ${counts.note} notes`,
  );
  return `${lines.join("\n")}\n`;
}

export function renderMarkdown(catalog: ErrorCatalog): string {
  const lines = [
    "# Error catalog",
    "",
    "<!-- Generated by ErrorAtlas. Edit descriptions and resolutions in erroratlas.catalog.json. -->",
    "",
    `Generated: ${catalog.generatedAt}`,
    "",
    `Documented errors: **${catalog.errors.length}**`,
    "",
  ];

  for (const error of catalog.errors) {
    lines.push(`## \`${escapeMarkdown(error.code)}\``, "");
    lines.push(`- **HTTP status:** ${error.status ?? "—"}`);
    lines.push(
      `- **Message:** ${error.message ? `\`${escapeMarkdown(error.message)}\`` : "—"}`,
    );
    if (error.problem) {
      lines.push(
        `- **Problem type:** ${error.problem.type ? `\`${escapeMarkdown(error.problem.type)}\`` : "—"}`,
        `- **Problem title:** ${error.problem.title ? `\`${escapeMarkdown(error.problem.title)}\`` : "—"}`,
        `- **Problem detail:** ${error.problem.detail ? `\`${escapeMarkdown(error.problem.detail)}\`` : "—"}`,
        `- **Problem instance:** ${error.problem.instance ? `\`${escapeMarkdown(error.problem.instance)}\`` : "—"}`,
      );
      const extensions = Object.entries(error.problem.extensions);
      if (extensions.length) {
        lines.push(
          `- **Problem extensions:** ${extensions
            .map(
              ([key, value]) =>
                `\`${escapeMarkdown(key)}=${escapeMarkdown(String(value))}\``,
            )
            .join(", ")}`,
        );
      }
    }
    if ((error.observedMessages?.length ?? 0) > 1) {
      lines.push("- **Observed messages:**");
      for (const message of error.observedMessages ?? []) {
        lines.push(`  - \`${escapeMarkdown(message)}\``);
      }
    }
    lines.push(
      `- **Description:** ${error.description || "_Not documented yet._"}`,
    );
    lines.push(
      `- **Resolution:** ${error.resolution || "_Not documented yet._"}`,
      "",
    );
    if (error.occurrences.length) {
      lines.push("**Defined at**", "");
      for (const occurrence of error.occurrences) {
        const proof = occurrence.evidence
          ? ` — proof: **${occurrence.evidence.confidence}** via ${renderEvidenceKinds(occurrence.evidence)}`
          : "";
        lines.push(
          `- \`${occurrence.file}:${occurrence.line}\` (${occurrence.language}, ${occurrence.constructor}${occurrence.flow ? `, ${occurrence.flow}` : ""})${proof}`,
        );
      }
      lines.push("");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

export function renderSarif(diagnostics: Diagnostic[]): string {
  const ruleIds = [...new Set(diagnostics.map((item) => item.ruleId))].sort();
  const sarif = {
    version: "2.1.0",
    $schema: "https://json.schemastore.org/sarif-2.1.0.json",
    runs: [
      {
        tool: {
          driver: {
            name: "ErrorAtlas",
            informationUri: "https://github.com/bvrtu/erroratlas",
            rules: ruleIds.map((id) => ({
              id,
              shortDescription: { text: humanize(id) },
            })),
          },
        },
        results: diagnostics.map((item) => sarifResult(item)),
      },
    ],
  };
  return `${JSON.stringify(sarif, null, 2)}\n`;
}

export function shouldFail(
  diagnostics: Diagnostic[],
  threshold: Exclude<Severity, "note">,
): boolean {
  if (threshold === "warning") {
    return diagnostics.some(
      (item) => item.severity === "error" || item.severity === "warning",
    );
  }
  return diagnostics.some((item) => item.severity === "error");
}

function sarifResult(diagnostic: Diagnostic): Record<string, unknown> {
  const result: Record<string, unknown> = {
    ruleId: diagnostic.ruleId,
    level:
      diagnostic.severity === "warning"
        ? "warning"
        : diagnostic.severity === "note"
          ? "note"
          : "error",
    message: { text: diagnostic.message },
  };
  if (diagnostic.location) {
    result.locations = [
      { physicalLocation: physicalLocation(diagnostic.location) },
    ];
  }
  if (diagnostic.evidence) {
    result.properties = {
      erroratlasConfidence: diagnostic.evidence.confidence,
      erroratlasEvidence: diagnostic.evidence.steps,
    };
  }
  return result;
}

function renderEvidenceKinds(
  evidence: NonNullable<Diagnostic["evidence"]>,
): string {
  return evidence.steps
    .map((step) => `\`${humanize(step.kind).toLowerCase()}\``)
    .join(" → ");
}

function physicalLocation(location: SourceLocation): Record<string, unknown> {
  return {
    artifactLocation: { uri: location.file },
    region: {
      startLine: location.line,
      startColumn: location.column,
      endLine: location.endLine,
      endColumn: location.endColumn,
    },
  };
}

function countSeverities(diagnostics: Diagnostic[]): Record<Severity, number> {
  const counts: Record<Severity, number> = { error: 0, warning: 0, note: 0 };
  for (const item of diagnostics) counts[item.severity] += 1;
  return counts;
}

function severityMark(severity: Severity): string {
  if (severity === "error") return "✖";
  if (severity === "warning") return "⚠";
  return "·";
}

function escapeMarkdown(value: string): string {
  return value.replace(/`/g, "\\`").replace(/\|/g, "\\|");
}

function humanize(value: string): string {
  return value
    .replace(/-/g, " ")
    .replace(/^./, (character) => character.toUpperCase());
}
